name: redstone_configuration_plugin
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Redstone plugin to get DI of configuration settings
homepage: https://github.com/redstone-dart/redstone_cookies_plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone_cookies_plugin
dependencies:
  redstone: ^0.6.0-beta.1
  redstone_mapper:
      path: "../redstone_mapper"
  path: ^1.3.5
